default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: chirs
  password: chirs
  port: 5432

development:
  <<: *default
  host: localhost
  database: userdashboard_test
